tlt_main:
    resource: "@TltMainBundle/Controller/"
    type:     annotation
    prefix:   /
tlt_admn:
    resource: "@TltAdmnBundle/Controller/"
    type:     annotation
    prefix:   /admin
tlt_ticket:
    resource: "@TltTicketBundle/Controller/DefaultController.php"
    type:   annotation
tlt_profile:
    resource: "@TltProfileBundle/Controller/"
    type: annotation
login_check:
    pattern:   /login_check
logout:
    path:     /logout