services:
    tlt.listener.maintenance:
        class: Tlt\MainBundle\Listener\MaintenanceListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }