parameters:
#    tlt_ticket.example.class: Tlt\TicketBundle\Example

services:
    ticket.twig.str_pad_extension:
        class: Tlt\TicketBundle\Twig\StringPaddingExtension
        tags:
            - { name: twig.extension }
     