<?php

namespace Tlt\AdmnBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemCategoryRepository extends EntityRepository
{

    public function findAllOrderedByName()
    {
        return $this->findBy(array(), array('department' => 'ASC', 'name' => 'ASC'));
    }

    public function findAllFromOneDepartmentOrderedByName($department)
    {
        return $this->findBy(
            array(
                'department' => $department
            ),
            array(
                'name' => 'ASC'
            )
        );
    }
}
