<?php

namespace Tlt\AdmnBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemPriceRepository extends EntityRepository
{
}
