#_welcome:
#    pattern:  /
#    defaults: { _controller: TltAdmnBundle:Default:index }
admn:
    path:     /admn
    defaults: { _controller: TltAdmnBundle:Default:index }
tlt_admn_departments_homepage:
    path:     /departments
    defaults: { _controller: TltAdmnBundle:Department:index }
tlt_admn_departments_add:
    path:     /departments/add
    defaults: { _controller: TltAdmnBundle:Department:add }
tlt_admn_departments_edit:
    path:     /departments/edit/{id}
    defaults: { _controller: TltAdmnBundle:Department:edit }
tlt_admn_departments_success:
    path:     /departments/success/{action}
    defaults: { _controller: TltAdmnBundle:Department:success }
tlt_admn_services_homepage:
    path:     /services
    defaults: { _controller: TltAdmnBundle:Service:index }
tlt_admn_services_add:
    path:     /services/add
    defaults: { _controller: TltAdmnBundle:Service:add }
tlt_admn_services_edit:
    path:     /services/edit/{id}
    defaults: { _controller: TltAdmnBundle:Service:edit }
tlt_admn_services_success:
    path:     /services/success/{action}
    defaults: { _controller: TltAdmnBundle:Service:success }
tlt_admn_systems_homepage:
    path:     /systems
    defaults: { _controller: TltAdmnBundle:System:index }
tlt_admn_systems_add:
    path:     /systems/add
    defaults: { _controller: TltAdmnBundle:System:add }
tlt_admn_systems_edit:
    path:     /systems/edit/{id}
    defaults: { _controller: TltAdmnBundle:System:edit }
tlt_admn_systems_success:
    path:     /systems/success/{action}
    defaults: { _controller: TltAdmnBundle:System:success }
#tlt_admn_owners_homepage:
#    path:     /list/owners
#    defaults: { _controller: TltAdmnBundle:Owner:index }
tlt_admn_owners_add:
    path:     /add/owners
    defaults: { _controller: TltAdmnBundle:Owner:add }
tlt_admn_owners_edit:
    path:     /edit/owners/{id}
    defaults: { _controller: TltAdmnBundle:Owner:edit }
tlt_admn_owners_success:
    path:     /owners/success/{action}
    defaults: { _controller: TltAdmnBundle:Owner:success }
tlt_admn_branch_homepage:
    path:     /branch
    defaults: { _controller: TltAdmnBundle:Branch:index }
tlt_admn_branch_add:
    path:     /branch/add
    defaults: { _controller: TltAdmnBundle:Branch:add }
tlt_admn_branch_edit:
    path:     /branch/edit/{id}
    defaults: { _controller: TltAdmnBundle:Branch:edit }
tlt_admn_branch_success:
    path:     /branch/success/{action}
    defaults: { _controller: TltAdmnBundle:Branch:success }
tlt_admn_locations_homepage:
    path:     /locations
    defaults: { _controller: TltAdmnBundle:Location:index }
tlt_admn_locations_add:
    path:     /locations/add
    defaults: { _controller: TltAdmnBundle:Location:add }
tlt_admn_locations_edit:
    path:     /locations/edit/{id}
    defaults: { _controller: TltAdmnBundle:Location:edit }
tlt_admn_locations_success:
    path:     /locations/success/{action}
    defaults: { _controller: TltAdmnBundle:Location:success }
tlt_admn_equipments_homepage:
    path:     /equipments
    defaults: { _controller: TltAdmnBundle:Equipment:index }
tlt_admn_equipments_add:
    path:     /equipments/add
    defaults: { _controller: TltAdmnBundle:Equipment:add }
tlt_admn_equipments_edit:
    path:     /equipments/edit/{id}
    defaults: { _controller: TltAdmnBundle:Equipment:edit }
tlt_admn_equipments_details:
    path:     /equipments/details/{id}
    defaults: { _controller: TltAdmnBundle:Equipment:details }
tlt_admn_equipments_success:
    path:     /equipments/success/{action}
    defaults: { _controller: TltAdmnBundle:Equipment:success }
tlt_admn_ajax_locations:
    path:     /fhs7/locations/{branch_id}/{all}
    defaults: {_controller: TltAdmnBundle:Ajax:locations, all: 0 }
tlt_admn_ajax_services:
    path:     /fhs7/services/{department_id}/{all}
    defaults: {_controller: TltAdmnBundle:Ajax:services, all: 0 }
tlt_admn_ajax_equipments:
    path:     /fhs7/equipments/{location_id}/{service_id}/{all}
    defaults: {_controller: TltAdmnBundle:Ajax:equipments, all: 0 }
tlt_admn_service_attrs_homepage:
    path:     /service_attrs
    defaults: { _controller: TltAdmnBundle:ServiceAttribute:index }
tlt_admn_service_attrs_add:
    path:     /service_attrs/add
    defaults: { _controller: TltAdmnBundle:ServiceAttribute:add }
tlt_admn_service_attrs_edit:
    path:     /service_attrs/edit/{id}
    defaults: { _controller: TltAdmnBundle:ServiceAttribute:edit }
tlt_admn_service_attrs_success:
    path:     /service_attrs/success/{action}
    defaults: { _controller: TltAdmnBundle:ServiceAttribute:success }
tlt_admn_service_attr_values_homepage:
    path:     /service_attr_values/{equipment_id}
    defaults: { _controller: TltAdmnBundle:ServiceAttributeValue:index }
tlt_admn_service_attr_values_add:
    path:     /service_attr_values/add/{equipment_id}
    defaults: { _controller: TltAdmnBundle:ServiceAttributeValue:add }
tlt_admn_service_attr_values_edit:
    path:     /service_attr_values/edit/{id}
    defaults: { _controller: TltAdmnBundle:ServiceAttributeValue:edit }
tlt_admn_service_attr_values_success:
    path:     /service_attr_values/success/{action}/{serviceAttributeValueId}
    defaults: { _controller: TltAdmnBundle:ServiceAttributeValue:success }
tlt_admn_mappings_homepage:
    path:     /mappings/{equipment_id}
    defaults: { _controller: TltAdmnBundle:Mapping:index }
tlt_admn_mappings_add:
    path:     /mappings/add/{equipment_id}
    defaults: { _controller: TltAdmnBundle:Mapping:add }
tlt_admn_mappings_edit:
    path:     /mappings/edit/{mapping_id}
    defaults: { _controller: TltAdmnBundle:Mapping:edit }
tlt_admn_mappings_delete:
    path:     /mappings/delete/{mapping_id}
    defaults: { _controller: TltAdmnBundle:Mapping:delete }
tlt_admn_mappings_success:
    path:     /mappings/success/{action}/{mapping_id}
    defaults: { _controller: TltAdmnBundle:Mapping:success }