parameters:
#    tlt_ticket.example.class: Tlt\TicketBundle\Example

services:
#    tlt_ticket.example:
#        class: %tlt_ticket.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    tlt.form.createTicket:
        class: Tlt\TicketBundle\Form\CreateTicketForm
        tags:
            - { name: form.type, alias: createTicket }
    tlt.form.flow.createTicket:
        class: Tlt\TicketBundle\Form\CreateTicketFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@tlt.form.createTicket" ] ]
    tlt.form.type.occuredAt:
        class: Tlt\TicketBundle\Form\Type\OccuredAtType
        tags:
            - { name: form.type, alias: form_type_occuredAt }
    tlt.form.type.announcedAt:
        class: Tlt\TicketBundle\Form\Type\AnnouncedAtType
        tags:
            - { name: form.type, alias: form_type_announcedAt }
    tlt.form.type.announcedBy:
        class: Tlt\TicketBundle\Form\Type\AnnouncedByType
        tags:
            - { name: form.type, alias: form_type_announcedBy }
    tlt.form.type.ticketAlloc:
        class: Tlt\TicketBundle\Form\Type\TicketAllocType
        tags:
            - { name: form.type, alias: form_type_ticketAlloc }
    tlt.form.type.shortDesc:
        class: Tlt\TicketBundle\Form\Type\ShortDescType
        tags:
            - { name: form.type, alias: form_type_shortDesc }
    tlt.form.type.ticketFix:
        class: Tlt\TicketBundle\Form\Type\TicketFixType
        tags:
            - { name: form.type, alias: form_type_ticketFix }
    tlt.form.type.ticketEquip:
        class: Tlt\TicketBundle\Form\Type\TicketEquipType
        tags:
            - { name: form.type, alias: form_type_ticketEquip }

# createTTicket
    tlt.form.createTTicket:
        class: Tlt\TicketBundle\Form\CreateTTicketForm
        tags:
            - { name: form.type, alias: createTTicket }
    tlt.form.flow.createTTicket:
        class: Tlt\TicketBundle\Form\CreateTTicketFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@tlt.form.createTTicket" ] ]
    tlt.form.type.tticketCreate:
        class: Tlt\TicketBundle\Form\Type\TTicketCreateType
        tags:
            - { name: form.type, alias: form_type_tticketCreate }
    tlt.form.type.tticketOwners:
        class: Tlt\TicketBundle\Form\Type\TTicketOwnersType
        tags:
            - { name: form.type, alias: form_type_tticketOwners }
    tlt.form.type.tticketFix:
        class: Tlt\TicketBundle\Form\Type\TTicketFixType
        tags:
            - { name: form.type, alias: form_type_tticketFix }

# reallocateTTicket
    tlt.form.reallocateTTicket:
        class: Tlt\TicketBundle\Form\ReallocateTTicketForm
        tags:
            - { name: form.type, alias: reallocateTTicket }
    tlt.form.flow.reallocateTTicket:
        class: Tlt\TicketBundle\Form\ReallocateTTicketFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@tlt.form.reallocateTTicket" ] ]
    tlt.form.type.tticketReallocate:
        class: Tlt\TicketBundle\Form\Type\TTicketReallocateType
        tags:
            - { name: form.type, alias: form_type_tticketReallocate }

# fixTTicket
    tlt.form.fixTTicket:
        class: Tlt\TicketBundle\Form\FixTTicketForm
        tags:
            - { name: form.type, alias: fixTTicket }
    tlt.form.flow.fixTTicket:
        class: Tlt\TicketBundle\Form\FixTTicketFlow
        parent: craue.form.flow
        scope: request
        calls:
            - [ setFormType, [ "@tlt.form.fixTTicket" ] ]